#!/bin/bash

# Set your Git user email and name
git config --global user.email "endywezy@gmail.com"
git config --global user.name "endywezy"

# Add all C files to git
git add *

# Check if there are any changes
if [[ -n $(git status -s) ]]; then
    # Iterate through each changed file
    git status -s | while read -r line; do
        # Extract the file name
        file=$(echo "$line" | awk '{print $2}')

        # Change the commit message based on the file extension
        if [[ "$file" == *.c ]]; then
            # Extract the file name without extension
            filename=$(basename -- "$file")
            filename_no_ext="${filename%.*}"

            # Change the commit message
            new_commit_msg="${filename_no_ext} - C changes"
            git commit -m "$new_commit_msg" "$file"
        fi
    done

    # Push changes to the remote repository
    git push
else
    echo "No changes to commit."
fi
